// Generated by CoffeeScript 1.6.2
(function() {
  var Mediator, Message, async, factory, listenerCollection, type,
    __slice = [].slice;

  Message = require("./message");

  factory = require("./factory");

  listenerCollection = require("./factory/collection");

  type = require("type-component");

  async = require("async");

  Mediator = (function() {
    /*
    */
    function Mediator() {
      this._listeners = {};
    }

    /*
    */


    Mediator.prototype.on = function() {
      var collection, listener, listeners, nameOrPlugin, nameParts;

      nameOrPlugin = arguments[0], listeners = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      if (nameOrPlugin.test) {
        return factory.push(nameOrPlugin);
      }
      nameParts = this._parse(nameOrPlugin);
      if (!(listener = this._listeners[nameParts.name])) {
        listener = this._listeners[nameParts.name] = {
          pre: [],
          post: []
        };
      }
      listeners = factory.create(this, listeners);
      if (nameParts.type) {
        collection = listener[nameParts.type];
        collection.push(listeners);
      } else {
        listener.callback = listeners;
      }
      return {
        dispose: function() {
          var i;

          if (collection) {
            return i = collection.indexOf(listeners);
          } else {
            return delete this._listeners[nameParts.name];
          }
        }
      };
    };

    /*
    */


    Mediator.prototype.once = function() {
      var listener, listeners, name;

      name = arguments[0], listeners = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      listeners.unshift(function(message, next) {
        listener.dispose();
        return next();
      });
      return listener = this.on.apply(this, [name].concat(listeners));
    };

    /*
    */


    Mediator.prototype.execute = function(nameOrMessage, data, next) {
      var chain, listener, msg;

      if (!nameOrMessage.__isCommand) {
        msg = new Message(nameOrMessage, data);
      } else {
        msg = nameOrMessage;
        next = data;
      }
      if (arguments.length === 2 && type(data) === "function") {
        next = data;
      }
      if (type(next) !== "function") {
        next = function() {};
      }
      listener = this._listeners[msg.name];
      if (!listener || !listener.callback) {
        return next(new Error("listener '" + msg.name + "' doesn't exist"));
      }
      chain = listener.pre.concat(listener.callback).concat(listener.post);
      return async.eachSeries(chain, (function(listener, next) {
        return listener(msg, next);
      }), function(err) {
        if (err != null) {
          return next(err);
        }
        return next.apply(null, [null].concat(__slice.call(msg.args)));
      });
    };

    /*
    */


    Mediator.prototype._parse = function(message) {
      var messageParts, name, t;

      messageParts = message.split(" ");
      name = messageParts.pop();
      t = messageParts.pop();
      return {
        type: t,
        name: name
      };
    };

    return Mediator;

  })();

  module.exports = function() {
    return new Mediator;
  };

}).call(this);
