// Generated by CoffeeScript 1.6.2
(function() {
  var Message;

  Message = (function() {
    /*
    */
    Message.prototype.__isCommand = true;

    /*
    */


    function Message(name, data, options, mediator, parent) {
      this.name = name;
      this.data = data;
      this.options = options != null ? options : {};
      this.mediator = mediator;
      this.parent = parent != null ? parent : void 0;
      this.args = [];
      this.root = this.parent ? this.parent.root : this;
    }

    /*
    */


    Message.prototype.child = function(name, options) {
      return new Message(name, this.data, options, this.mediator, this);
    };

    return Message;

  })();

  module.exports = Message;

}).call(this);
