// Generated by CoffeeScript 1.6.2
(function() {
  var async, type;

  type = require("type-component");

  async = require("async");

  module.exports = {
    test: function(options) {
      return type(options.options) === "array";
    },
    create: function(options) {
      if (options.options.length === 1) {
        return options.options[0];
      }
      return function(message, next) {
        var _this = this;

        return async.eachSeries(options.options, (function(listener, next) {
          return listener.call(_this, message, next);
        }), next);
      };
    }
  };

}).call(this);
