// Generated by CoffeeScript 1.6.2
(function() {
  var type,
    __slice = [].slice;

  type = require("type-component");

  module.exports = {
    test: function(options) {
      return type(options.listener) === "function";
    },
    create: function(options) {
      var fn;

      fn = options.listener;
      return function(message, next) {
        return fn(message, function() {
          var args, err;

          err = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
          if (err != null) {
            return next(err);
          }
          if (args.length) {
            message.args = args;
          }
          return next();
        });
      };
    }
  };

}).call(this);
