// Generated by CoffeeScript 1.6.2
(function() {
  var factories;

  factories = require("factories");

  module.exports = factories.any([require("./obj"), require("./fn"), require("./str"), require("./array")]);

}).call(this);
