// Generated by CoffeeScript 1.6.2
(function() {
  var collection, factories;

  factories = [require("./obj"), require("./fn"), require("./ref"), collection = require("./collection")];

  module.exports = {
    push: function(factory) {
      return factories.push(factory);
    },
    create: function(mediator, listeners) {
      var listener, options, tester, tlisteners, _i, _j, _len, _len1;

      tlisteners = [];
      for (_i = 0, _len = listeners.length; _i < _len; _i++) {
        listener = listeners[_i];
        options = {
          mediator: mediator,
          listener: listener
        };
        for (_j = 0, _len1 = factories.length; _j < _len1; _j++) {
          tester = factories[_j];
          if (tester.test(options)) {
            tlisteners = tlisteners.concat(tester.create(options));
          }
        }
      }
      if (tlisteners.length === 1) {
        return tlisteners[0];
      }
      return collection.create({
        mediator: mediator,
        listener: tlisteners
      });
    }
  };

}).call(this);
