// Generated by CoffeeScript 1.6.2
(function() {
  var async, type;

  type = require("type-component");

  async = require("async");

  module.exports = {
    test: function(options) {
      return type(options.options) === "object";
    },
    create: function(options) {
      var mediator, names;

      names = Object.keys(options.options);
      mediator = options.mediator;
      return function(message, next) {
        return async.eachSeries(names, (function(name, next) {
          return mediator.execute(name, names.child(name), next);
        }), next);
      };
    }
  };

}).call(this);
