// Generated by CoffeeScript 1.6.2
(function() {
  var async, type;

  type = require("type-component");

  async = require("async");

  module.exports = {
    test: function(options) {
      return type(options.listener) === "object";
    },
    create: function(options) {
      var mediator, refs;

      refs = Object.keys(options.listener);
      mediator = options.mediator;
      return function(message, next) {
        return async.eachSeries(refs, (function(ref, next) {
          return mediator.execute(message.child(ref, options.listener[ref]), next);
        }), next);
      };
    }
  };

}).call(this);
