// Generated by CoffeeScript 1.6.2
(function() {
  var type;

  type = require("type-component");

  module.exports = {
    test: function(options) {
      return type(options.listener) === "string";
    },
    create: function(options) {
      var mediator, ref;

      mediator = options.mediator;
      ref = options.listener;
      return function(message, next) {
        return mediator.execute(message.child(ref), next);
      };
    }
  };

}).call(this);
