// Generated by CoffeeScript 1.6.2
(function() {
  var type;

  type = require("type-component");

  module.exports = {
    test: function(options) {
      return type(options.options) === "string";
    },
    create: function(options) {
      var mediator, name;

      mediator = options.mediator;
      name = options.options;
      return function(message, next) {
        return mediator.execute(message.child(name), next);
      };
    }
  };

}).call(this);
